######### 锚点 start #######
# 策略组相关
pr: &pr 
     type: select
     proxies: [⚡ 全局规则,🇭🇰 香港手动,🇨🇳 台湾手动,🇯🇵 日本手动,🇸🇬 新加坡手动,🇰🇷 韩国手动,🇺🇲 美国手动,🇩🇪 德国手动,🇭🇰 香港自动,🇨🇳 台湾自动,🇯🇵 日本自动,🇸🇬 新加坡自动,🇰🇷 韩国自动,🇺🇲 美国自动,🇩🇪 德国自动,其它地区,全部节点,DIRECT]

#这里是订阅更新和延迟测试相关的
p: &p
    type: http
    interval: 3600
    health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}

#规则集相关
c: &c {type: http, interval: 86400, behavior: classical, format: text}
m: &m {type: http, interval: 86400, behavior: domain, format: mrs}

#延迟测试
t: &t {type: url-test, url: https://www.gstatic.com/generate_204, interval: 300, tolerance: 100}

######### 锚点 end #######

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  赔钱:
    <<: *p
    url: ""
    path: ./proxy_provider/赔钱.yaml
    override:
      skip-cert-verify: true
    exclude-filter: "套餐|流量|重置"
    


mode: rule
ipv6: false
allow-lan: true
mixed-port: 7890
unified-delay: true
tcp-concurrent: true
external-controller: 0.0.0.0:9090

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 2231, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  device: mihomo

dns:
  enable: true
  ipv6: false
  respect-rules: true
  enhanced-mode: redir-host
  nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  proxy-server-nameserver:
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    "rule-set:cn_domain":
      - https://120.53.53.53/dns-query
      - https://223.5.5.5/dns-query
    "rule-set:geolocation-!cn":
      - "https://dns.cloudflare.com/dns-query"
      - "https://dns.google/dns-query"
            
proxy-groups:
  - name: ⚡ 全局规则
    type: select
    proxies: [🇭🇰 香港手动,🇨🇳 台湾手动,🇯🇵 日本手动,🇸🇬 新加坡手动,🇰🇷 韩国手动,🇺🇲 美国手动,🇩🇪 德国手动,🇭🇰 香港自动,🇨🇳 台湾自动,🇯🇵 日本自动,🇸🇬 新加坡自动,🇰🇷 韩国自动,🇺🇲 美国自动,🇩🇪 德国自动,其它地区,全部节点,DIRECT]

  - name: 🎥 Emby服务
    <<: *pr

  - name: 📲 电报信息
    <<: *pr
    
  - name: ✈️ 测速服务
    <<: *pr

  - name: 🇬 谷歌服务
    <<: *pr

  - name: 📹 油管视频
    <<: *pr

  - name: Ⓜ️ 微软服务
    <<: *pr

  - name: 🤖 OpenAI
    <<: *pr

  - name: ▶️ 奈飞服务
    <<: *pr

  - name: 🎵 Spotify
    <<: *pr

  - name: 🐟 漏网之鱼
    <<: *pr
  
#地区分组
  - name: 🇭🇰 香港手动
    type: select
    include-all: true
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 🇨🇳 台湾手动
    type: select
    include-all: true
    filter: "(?i)台|新北|彰化|TW|Taiwan"

  - name: 🇸🇬 新加坡手动
    type: select
    include-all: true
    filter: "(?i)(新|sg|singapore)"

  - name: 🇯🇵 日本手动
    type: select
    include-all: true
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"

  - name: 🇰🇷 韩国手动
    type: select
    include-all: true
    filter: "(?i)(KR|Korea|KOR|首尔|韩|韓|春川)"

  - name: 🇺🇲 美国手动
    type: select
    include-all: true
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"

  - name: 🇩🇪 德国手动
    type: select
    include-all: true
    filter: "(?i)(德|DE|DEU|Germany)"
    
  - name: 🇭🇰 香港自动
    <<: *t
    include-all: true
    filter: "(?i)港|hk|hongkong|hong kong"

  - name: 🇨🇳 台湾自动
    <<: *t
    include-all: true
    filter: "(?i)台|新北|彰化|TW|Taiwan"

  - name: 🇸🇬 新加坡自动
    <<: *t
    include-all: true
    filter: "(?i)(新|sg|singapore)"

  - name: 🇯🇵 日本自动
    <<: *t
    include-all: true
    filter: "(?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan"

  - name: 🇰🇷 韩国自动
    <<: *t
    include-all: true
    filter: "(?i)(KR|Korea|KOR|首尔|韩|韓|春川)"

  - name: 🇺🇲 美国自动
    <<: *t
    include-all: true
    filter: "(?i)美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States"

  - name: 🇩🇪 德国自动
    <<: *t
    include-all: true
    filter: "(?i)(德|DE|DEU|Germany)"

  - name: 其它地区
    type: select
    include-all: true
    filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇹🇼|港|hk|hongkong|台|tw|taiwan|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|德|DE|DEU|Germany|新|sg|KR|Korea|KOR|首尔|韩|韓|春川|singapore|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)).*"

  - name: 全部节点
    type: select
    include-all: true

rules:  
#分流
  - RULE-SET,lan,DIRECT
  - DST-PORT,8080,✈️ 测速服务
  - RULE-SET,speedtest,✈️ 测速服务
  - RULE-SET,emby,🎥 Emby服务
  - RULE-SET,telegram,📲 电报信息
  - RULE-SET,openai,🤖 OpenAI
  - RULE-SET,youtube,📹 油管视频
  - RULE-SET,google,🇬 谷歌服务
  - RULE-SET,microsoft,Ⓜ️ 微软服务
  - RULE-SET,netflix,▶️ 奈飞服务
  - RULE-SET,spotify,🎵 Spotify
  - RULE-SET,ChinaASN,DIRECT,no-resolve
  - RULE-SET,cn_domain,DIRECT  
  - RULE-SET,geolocation-!cn,🐟 漏网之鱼
  - MATCH,🐟 漏网之鱼
  
rule-providers:
  lan:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list"
    path: ./rules/Lan.list
  ChinaASN:
    <<: *c
    url: "https://cf-workers-text2kv-eh7.pages.dev/ChinaASN.list?token=071496"
    path: ./rules/ChinaASN.list
  emby:
    <<: *c
    url: "https://cf-workers-text2kv-eh7.pages.dev/emby.list?token=071496"
    path: ./rules/emby.list
  telegram:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list"
    path: ./rules/telegram.list
  speedtest:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list"
    path: ./rules/speedtest.list
  microsoft:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list"
    path: ./rules/microsoft.list
  openai:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"
    path: ./rules/OpenAI.list
  youtube:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list"
    path: ./rules/youtube.list
  google:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list"
    path: ./rules/google.list
  spotify:
    <<: *c
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list"
    path: ./rules/Spotify.list
  netflix:
    <<: *c
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list"
    path: ./rules/netflix.list
  cn_domain:
    <<: *m
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"
    path: ./rules/cn.mrs
  geolocation-!cn:
    <<: *m
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"
    path: ./rules/geolocation-!cn.mrs